<?php

namespace Illuminate\Routing\Dumped;

use Illuminate\Routing\Route;
use Illuminate\Routing\RouteCollection;
use Illuminate\Routing\RouteCompiler;

class UrlInformationDumper
{
    public function dump(RouteCollection $routeCollection)
    {
        list ($byName, $byAction) = $this->formatRouteInformation($routeCollection);
        $byName = var_export($byName, true);
        $byAction = var_export($byAction, true);

        $code = <<<EOF
<?php

// THIS CODE IS GENERATED BY LARAVEL

class DumpedUrlInformation extends \Illuminate\Routing\Dumped\UrlInformation
{
    protected \$byName = $byName;
    protected \$byAction = $byAction;
}
EOF;

        return $code;
    }

    protected function formatRouteInformation(RouteCollection $routeCollection)
    {
        $byName = [];
        $byAction = [];

        /** @var Route $route */
        foreach ($routeCollection as $index => $route) {
            $name = $route->getName() ?: sprintf('route_at_index_%d', $index);
            $information = (new RouteCompiler($route))->getRouteInformation();

            $byName[$name] = $information;

            if ($action = $route->getAction() && isset($action['controller'])) {
                $byAction[trim($action['controller'], '\\')] = $name;
            }
        }

        return [$byName, $byAction];
    }
}